### PR TITLE
Add instructions on how to set default indenting as in issue #50

### PR DESCRIPTION
**Pull request by dylan-chong**
Hopefully a good enough for now fix for #50

### CODE REVIEW

**Comment by tpope** [comment]
I think instead of the guard, you probably want to use `:setglobal` for the top level definitions.

**Comment by dylan-chong** [comment]
@tpope fixed

**Comment by dylan-chong** [comment]
@tpope I just realise that your solution of using set global is actually a equivalent to removing those lines altogether.

Using set globals, when I open a new file indenting is still set to tabs. Should I just revert the changes back to what it was before with the guard?

**Comment by aleclarson** [comment]
Why does the file type-specific command go before the globals? (not a vim expert)

Do I put the `setglobal` commands before something like [vim-plug](https://github.com/junegunn/vim-plug)?

**Comment by dylan-chong** [comment]
@aleclarson i have just updated the instructions can you have a look at it again

**Comment by aleclarson** [comment]
@dylan-chong `set` works great. Thanks!

**Comment by dylan-chong** [comment]
@aleclarson Would you mind hitting approve once you are confident that it works perfectly? I assume @tpope is a little busy, so hopefully this might speed up getting this merged

**Comment by dylan-chong** [comment]
@aleclarson extendtab?

Could you clarify what you mean? I am not sure i understand what you mean

**Comment by aleclarson** [comment]
@dylan-chong That was a typo. I meant `expandtab`

**Comment by aleclarson** [comment]
You've tried reproducing what I said above?

**Comment by dylan-chong** [comment]
Sorry I don't understand your instructions. Could you provide your Jason file and provide an exact list of commands/keystrokes to run?

**Comment by minhduc0711** [comment]
I tried this and it overrides vim-sleuth detection for some reason.
I'm not really sure about `_has_set_default_indent_settings`, idk where it is set in sleuth.vim...

**Comment by dylan-chong** [comment]
@minhduc0711 _has_set_default_indent_settings is defined only in the snippet

**Comment by minhduc0711** [comment]
I see, then how does it know if vim-sleuth has detected the indent settings or not?

**Comment by dylan-chong** [comment]
It does not :( . iirc it relies on running before sleuth detection is triggered (because the vimrc is loaded before the file being edited is loaded)

**Comment by minhduc0711** [comment]
Hmm in that case I don't know why this is not working for me.
If I open this tab-indented snippet https://pastebin.com/raw/LHvPPuW8, it would ignore the tabs and default to 4 spaces. Could you please try with your setup?

**Pull request closed without merging**
