### PR TITLE
Add a spaces heuristics to set the shiftwidth

### PR DESCRIPTION
**Pull request by XaF**
Instead of only looking for the smallest number of spaces used, this allows to search for the tinyest most used number of spaces.

In that idea, if one line in the file does not follow the rest of the file, it will not break the computation of shiftwidth. This is helpful when working on large files in which you do not want to touch other parts when not needed or maintained by other people.

### CODE REVIEW

**Comment by ltratt** [comment]
I like the idea of this PR as this a problem I frequently face. I think this PR should mean that given this file:

```
a
    b
    c
  d
```

shiftwidth gets set to 4 (since there are two lines with an indent of 4 and only one with an indent of 2). But `shiftwidth` still gets set to 2. If I delete the line `  d` then `shiftwidth` is set to 4.

Am I missing out on something obvious perhaps?

**Comment by XaF** [comment]
4 is a multiple of 2, so it considers that 4 is actually double indent as there is a line with 2.
This allows to consider files like:
```
a
  bb
    ccc
    ddd
    eee
```

**Comment by ltratt** [comment]
Ah, I see. I guess I was expecting something slightly different, but thinking about it a bit more, it won't be easy. For example here's a file which sleuth (IMHO "incorrectly") guesses as having a `shiftwidth` of 2:

```
$ grep "^  [^ ]" parser.rs|wc -l
       9
$ grep "^    [^ ]" parser.rs|wc -l
      77
```

Here's the full count (indent=instances): 2=9, 4=77, 8=57, 12=24, 16=17, 20=25, 24=2. Finding a heuristic which realises that 2 is the odd one out might be challenging...

**Comment by SammysHP** [comment]
@ltratt 
Some months ago I wrote my own indentation detection – called [*heurindent*](https://github.com/SammysHP/vim-heurindent) (for "heuristic indentation"). Here's the debug output I get for your file:

```
Linetype histogram: {'soft': 125, 'comment': 0, 'spaces': 86, 'total': 211, 'hard': 0}                                                                                                                                                                         
Indentation histogram: {'2': 9, '4': 77, '12': 24, '8': 57, '20': 25, '16': 17, '24': 2}
Space heuristics:   {'2': 114.74072, '3': 12.70743, '4': 157.55936, '5': 12.8, '6': 20.224, '7': 0, '8': 71.88}
Determined options: {'shiftwidth': '4', 'expandtab': 1}
```

The important part:

```
'2': 114.74072
'4': 157.55936
```

So it correctly detects four spaces as the indentation.

**Comment by sheerun** [comment]
Unfortunately such heuristics can be often wrong, and minimal tab gives best results. For example following file:

```py
def example(name):
  if something():
    foo()
    bar()
    baz()
    fiz()
    fiz()
    faz()
```

Statistical-based algorithms, including @SammysHP's return 4-spaces indentation, while simple algorithm correctly returns 2

**Comment by tpope** [comment]
That was my gut reaction too. You can maybe use statistical analysis to rule out oddballs like 3 but for the powers of 2 it's a nonstarter.

**Comment by sheerun** [comment]
@tpope Approach of counting increments in indentation instead of selecting minimum indentation (i.e. #53) look good though

**Pull request closed without merging**
