### PR TITLE
Calculate shiftwidth by statistic indent changes

### PR DESCRIPTION
**Pull request by chen3feng**

### CODE REVIEW

**Comment by sheerun** [comment]
this won't work if file has indented function like so:

```
function() {
  foo = bar
  while (true) {
    fizfuz()
    fizfuz()
    fizfuz()
    fizfuz()
  }
}
```

The file above should have indent of 2, even though most frequent indent is 4

**Comment by danielfalk** [comment]
@sheerun It looks like the code is accounting for that.  The "fizfuz()" lines which are indented by 4 are seen to be indented by 2, since they are indented only 2 past the previous indentation.

On line 101 of sleuth.vim: 
`let indent_inc = indent - prev_indent`

**Comment by sheerun** [comment]
@danielfalk I think you're right, sorry! :)

**Comment by sheerun** [comment]
btw. this is useful for example in fortran, where shiftwidth should be 2 even though first indent must be 6, here's code:

```
C      call DGEMM('T','N',3,3,3,1.d0,Fdef,3,Fdef,3,0.d0,Cdef,3)
      do j=1,ndm
        do k=1,ndm
          do i=1,ndm
            Cdef(i,j) = Cdef(i,j) + Fdef(k,i)*Fdef(k,j)
          enddo
        enddo
      enddo
```

Also in fortran there can be number in the first 6 characters, and continuation statement must be at 5 indents...

```
C AREA OF A TRIANGLE - HERON'S FORMULA
C INPUT - CARD READER UNIT 5, INTEGER INPUT
C OUTPUT -
C INTEGER VARIABLES START WITH I,J,K,L,M OR N
      READ(5,501) IA,IB,IC
  501 FORMAT(3I5)
      IF(IA.EQ.0 .OR. IB.EQ.0 .OR. IC.EQ.0) STOP 1
      S = (IA + IB + IC) / 2.0
      AREA = SQRT( S * (S - IA) * (S - IB) * (S - IC) )
      WRITE(6,601) IA,IB,IC,AREA
 2601 FORMAT(4H A= ,I5,5H  B= ,I5,5H  C= ,I5,8H  AREA= ,F10.2,
     $13H SQUARE UNITS)
      STOP
      END
```

**Comment by sheerun** [comment]
I've implemented something like this in vim-polyglot:

https://github.com/sheerun/vim-polyglot/commit/903793ac04b9fbc06f3e0b6e63113a0dd4c87940

**Comment by sheerun** [comment]
btw. algorithm works better if all lines at given indent are toward given "increment". For example consider first 64 lines of following c++ file: https://github.com/llvm/llvm-project/blob/master/clang/lib/AST/APValue.cpp

If you use this algorithm you get indent of 4, if you count all lines indented, not just number of indents, you get correct answer 2

**Comment by tpope** [comment]
Went with a heavily modified version of this, thanks.

> btw. algorithm works better if all lines at given indent are toward given "increment". For example consider first 64 lines of following c++ file: https://github.com/llvm/llvm-project/blob/master/clang/lib/AST/APValue.cpp

Working link: https://github.com/llvm/llvm-project/blob/3ac561d8c348a7bdc0313a268d5b3b4dcac118a2/clang/lib/AST/APValue.cpp
 
> If you use this algorithm you get indent of 4, if you count all lines indented, not just number of indents, you get correct answer 2

I get 4 no matter which way I try it.  The problem is the hanging indent in functions like this:

```c++
void TypeInfoLValue::print(llvm::raw_ostream &Out,
                           const PrintingPolicy &Policy) const {
  Out << "typeid(";
  QualType(getType(), 0).print(Out, Policy);
  Out << ")";
}
```

I take it the goal is to count this as 3 indented lines rather than 1 indent, but thanks to that 27 space hanging indent, it gets counted as 0 either way.

Fortunately, the file is detected correctly if you increase the line limit, so I'm gonna set this aside until a better example is found.

**Pull request closed without merging**
