### PR TITLE
Minor performance optimization in s:guess

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by vheon** [comment]
Did you actually benchmark this or is just a feeling? I'm especially talking about the regex condition.

**Comment by blueyed** [comment]
Just a feeling, sorry.

But here we go:

```
% time vim -u NONE -c 'let s = "" | for i in range(1, 1000000) | if !len(s) | continue | sleep 1 | endif | endfor | q'                                       
vim -u NONE -c   2.20s user 0.09s system 99% cpu 2.297 total

% time vim -u NONE -c 'let s = "" | for i in range(1, 1000000) | if s =~# '"'"'^\s*$'"'"' | continue | sleep 1 | endif | endfor | q' 
vim -u NONE -c   3.27s user 0.08s system 99% cpu 3.363 total
```

So the current method is ~150% slower.

It's marginal after all, compared to things like not looking at 1024 lines all the time, of course.

**Comment by vheon** [comment]
If you actually want this to be faster you should re-implement the algorithm with python or lua. I have them both at https://github.com/vheon/vim-sleuth/tree/lua if you want to try/profile them.

**Comment by blueyed** [comment]
@vheon 
Interesting.  But not profiled?

FWIW: I just looked at vim-sleuth again, because https://github.com/roryokane/detectindent was misbehaving on some `libXft/src/xftfreetype.c`, but I will probably stick to it anyway for now.

**Comment by vheon** [comment]
> Interesting. But not profiled?

I did but I didn't post them anywhere IIRC and I lost the data :sob: But it where Lua < Python < VimL, don't remember the percentage though.

**Pull request merged**
